# docker-compose.yml
version: '3.8'

services:
  whatsapp-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./qr-codes:/usr/src/app/qr-codes
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge